version: '3.1'
services:
    app:
        container_name: docker-springboot-postgresql
        image: docker-springboot-postgresql
        build: ./
        ports:
            - "8080:8080"
        depends_on:
            - postgresqldb
    postgresqldb:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=postgres
            - POSTGRES_DB=bookstore